title: Tevfik Türkoğlu
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Tevfik Türkoğlu
avatar: /logo.png
email: tevfikturkoglu45@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
X:
  username: thousaba
  card: summary
logo: logo.png
social:
  name: Tevfik Türkoğlu
  links:
    - https://x.com/thousaba
    - https://github.com/thousaba
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
